[build]
  command = "npm install && npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_FLAGS = "--legacy-peer-deps"

# Remove the plugin section for now
# [[plugins]]
#  package = "@netlify/plugin-nextjs" 