[build]
  command = "NODE_ENV=production npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_PRIVATE_TARGET = "server"
  NODE_OPTIONS = "--max_old_space_size=4096"
  NODE_VERSION = "18.17.0" 